### ISSUE TITLE
Can't start via stitch script

### ISSUE THREAD

**Issue by R4ynor** [jsreynaud/kicad-action-scripts#16]
I get this error window after trying to start the script:

![image](https://user-images.githubusercontent.com/9499061/66391801-647d9f80-e9ce-11e9-8391-86dc17a20612.png)

I'm using KiCad 5.14 in Windows 10.

**Comment by easyw** [comment]
Please have a try with my pr code
https://github.com/jsreynaud/kicad-action-scripts/pull/15
Hoping this will be merged.

**Comment by jsreynaud** [comment]
The PR #15 was merged few minutes ago...
