### ISSUE TITLE
Out of the grid stitching

### ISSUE THREAD

**Issue by TheColonelYoung** [jsreynaud/kicad-action-scripts#17]
I tried to fill ground plane with via. Based on example picture in README I expected vias to be placed into grid. But vias are placed out of the grid. In configuration for stitching is random placing of vias disabled (image below). I thought that would be caused by round corners, but it was nearly same after making sharp corners. I tried to use star pattern or random it but was very similiar. I also try to use different setting for via size, grid and clearence but also was out of grid.

Kicad Version: 5.1.4-e60b266~84~ubuntu18.04.1, release build
Via stitching plugin: commit 5c7670c4fa897111d8e225776367ce623d5d41e2
![Kicad_via_stitching_settings](https://user-images.githubusercontent.com/14985120/66721606-9777c700-ee04-11e9-86d9-8e2a5487af10.png)
![Kicad_via_stitching](https://user-images.githubusercontent.com/14985120/66721607-99da2100-ee04-11e9-9d5d-bb813f62f6f9.png)

Also in empty project with rectangular PCB with only one part vias was not in grid. Setting was same as on picture above.
![Kicad_vias_empty_project](https://user-images.githubusercontent.com/14985120/66721752-086bae80-ee06-11e9-9e39-c613a8195e92.png)

Should vias be even placed to grid or I misinterpret the image?

**Comment by jsreynaud** [comment]
Last commit fix that...
