### ISSUE TITLE
Vias out of gnd areas

### ISSUE THREAD

**Issue by mtiutiu** [jsreynaud/kicad-action-scripts#2]
Hi,

First of all good job for providing this plugin - it's a really missing feature of KiCAD. I noticed that most of the time I get vias out of the GND filled zones which appear then as unconnected pads of course. Maybe it has to do with the method used to calculate filled areas/zones and bounds.

Here are some screenshots related to this issue.
https://pasteboard.co/hDX4PNf0J.png
https://pasteboard.co/hDXnUrMH0.png
https://pasteboard.co/hDXFOl392.png
https://pasteboard.co/hDXTPd6bg.png

Thanks.

**Comment by jsreynaud** [comment]
Hi,

There is a function to detect hit on edge (HitTestForEdge) but the clearance is hard coded in KiCad. I had push an update but It will not work in general case.
