### ISSUE TITLE
Silkscreen Unreadable With Placed Vias

### ISSUE THREAD

**Issue by brandondrury** [jsreynaud/kicad-action-scripts#24]
It would be great if there was an option to exclude the placement of vias on top of silkscreen.  If vias are placed on top of labels to pins, they've turned out unreadable on a few boards I've made.

Thanks!

**Comment by jsreynaud** [comment]
Please check on v5.1 branch. Commit c8a8bf80aa6fa6de318377c994e2ddd91f973fe1 should add this feature ;)

**Comment by Weissnix4711** [comment]
Was this ever added to the KiCad 6 branch? Many of my board's component references have become unreadable, or just look ugly.

I've found I can exclude vias from being placed in certain areas by using keepout zones, but that is quite impractical to manually place zones over each and every graphical element.
