### ISSUE TITLE
Porting to 6.0

### ISSUE THREAD

**Issue by Spirit532** [jsreynaud/kicad-action-scripts#27]
The 6.0 release is coming up soon, but none of these plugins work with 6 for various reasons. Is there a port planned?

**Comment by Qbort** [comment]
I confirm it doesn't work on latest nightly install:
![image](https://user-images.githubusercontent.com/16581353/106039713-5ecf3000-60d1-11eb-8bcb-c3b37f8c025e.png)

**Comment by jsreynaud** [comment]
Yes It's planned. I'm working on it...

**Comment by MANONG571** [comment]
So do you know how to figure it out?

**Comment by jsreynaud** [comment]
Yes. I have to do that. It's on my todo list ;)
