### ISSUE TITLE
Crash on start ViaStitching plugin

### ISSUE THREAD

**Issue by dj140** [jsreynaud/kicad-action-scripts#30]
I‘m using kicad 5.1.5 version
![version](https://user-images.githubusercontent.com/33819388/107858053-050a8c00-6e6d-11eb-80dd-d56ab371a88e.PNG)
after start ViaStitching plugin 
![error](https://user-images.githubusercontent.com/33819388/107857992-ce347600-6e6c-11eb-836f-4be37fc5e5b4.PNG)

**Comment by OmarAlkassab** [comment]
Same error here.

![2021-02-22 14_53_26-Window](https://user-images.githubusercontent.com/31249807/108712107-fa13c380-751e-11eb-96af-9b0fe8a8b531.png)
![2021-02-22 15_02_54-Window](https://user-images.githubusercontent.com/31249807/108712182-1283de00-751f-11eb-92ad-4a17830adc77.png)

**Comment by josenestorpardoherrera** [comment]
Same error here. I will have to do it manually :s
![Error](https://user-images.githubusercontent.com/35857563/109138258-76461b00-775a-11eb-8e64-87f3973dc919.jpg)

**Comment by jsreynaud** [comment]
Are you sure that you get the v5.1 branch of the plugin ? The master branch is for nightly build and I had recheck everything. In V5.1 its working correctly.

**Comment by OmarAlkassab** [comment]
> Are you sure that you get the v5.1 branch of the plugin ? The master branch is for nightly build and I had recheck everything. In V5.1 its working correctly.

Yes you are right, it worked perfectly when I used the v5.1 branch of the plugin.
![Untitled](https://user-images.githubusercontent.com/31249807/109702135-83209f80-7b9c-11eb-92b8-3ee0626ffe8e.png)

**Comment by wojiaodingsan** [comment]
> Are you sure that you get the v5.1 branch of the plugin ? The master branch is for nightly build and I had recheck everything. In V5.1 its working correctly.

I have the same problem when using the default version, after changed to v5.1 it solved, thanks.

**Comment by arthurmagill** [comment]
Same error here. Version info:

Application: KiCad
Version: 5.1.9-73d0e3b20d~88~ubuntu18.04.1, release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Platform: Linux 4.15.0-137-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.22
    Boost: 1.65.1
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.58.0
    Compiler: GCC 7.5.0 with C++ ABI 1011
Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

**Comment by jsreynaud** [comment]
@arthurmagill . Please check that the plugin branch you use is V5.1
