### ISSUE TITLE
SWIG : AttributeError: 'module' object has no attribute 'GetName'

### ISSUE THREAD

**Issue by synaption** [jsreynaud/kicad-action-scripts#35]
Maybe this is user error, but I'm going to guess it's a windows related error.  When I run the Via Stitching plugin in kicad 5.99 it gives me the below error.  Sorry I cannot copy and paste the text.  
![image](https://user-images.githubusercontent.com/29110580/130291475-019eadf8-ac9c-4306-99af-eaac09e75e68.png)

**Comment by jsreynaud** [comment]
As you are using KiCad dev branch (5.99), please provide complete version information of KiCad you use (available in about dialog of KiCad)
