### ISSUE TITLE
Python Error in Via Stitching Generator

### ISSUE THREAD

**Issue by albtronics** [jsreynaud/kicad-action-scripts#36]
When I open **Via Stitching Generator** Plugin, it shows this error:

![Via_Stiching_Error](https://user-images.githubusercontent.com/64254495/130455832-62400888-7bf8-46e3-befe-78765440b08f.PNG)
I think its due to the conflicting versions of python. ( _KiCad Windows version's core is running on Python 2.7_ )
Please help.

_My KiCad version(on Windows 10):_

![Kicad_Version](https://user-images.githubusercontent.com/64254495/130456201-6177ab79-4d88-418b-b830-997b884fbb38.PNG)

Also, I have a request, It would be great, if there is a quick **Light/Dark Theme Toggle plug-in.**

Thank you in advance, : )

**Comment by jsreynaud** [comment]
As I see you use KiCad 5.1.9 and the version of Via Stitching Generator is "master" branch that is supposed to work only with "dev" version of KiCad.

You have to checkout the "v5.1" branch of Via Stitching Generator to fix that (see README.md).

**Comment by albtronics** [comment]
Thank you so much for replying Reynaud. *I didn't see that branch
initially.*

*Please consider making a Light/Dark theme toggler plugin for KiCad.*

*Warm regards*
*Albin Joseph C.R*

**Comment by jsreynaud** [comment]
Ok. for making a Light/Dark theme toggler plugin for KiCad, I create a new issue for that.

Regards,

**Comment by albtronics** [comment]
Reynaud, one more help. Could you please check this out:
https://github.com/easyw/RF-tools-KiCAD/issues/27
This plugin might have a similar issue (*nightly build and the normal build*
).
But, its author had put only one repo.

It would be very useful if that issue had been solved.

Warm Regards
Albin Joseph C.R
