### ISSUE TITLE
Via Stitching Generator - Kicad 5.1.2 Windows 10

### ISSUE THREAD

**Issue by Sani300** [jsreynaud/kicad-action-scripts#38]
Hi, 

Thanks a lot for this plugins ! 
Circular zone work well, but I have some issue with Via Stitching Generator on Kicad 5.1.2 on Windows 10 with python 2.7.6

When I start plugins I have this error :  
![ViaStitching](https://user-images.githubusercontent.com/8338638/132006015-7bd6c6a6-8c4a-4409-b8d0-22426248d0bb.PNG)

Do you know why?!

**Comment by jsreynaud** [comment]
I think you are not used the good version of this plugin. Please checkout the v5.1 branch. The "master" branch is for next version of KiCad.
And tell me...

**Comment by Sani300** [comment]
Top ! Thanks
