### ISSUE TITLE
Via Stitching Generator - Kicad 5.1.2 Windows 10

### ISSUE THREAD

**Issue by Sani300** [jsreynaud/kicad-action-scripts#39]
Hi, 

Still a problem with revision : 523525bbc
![ViaStitching](https://user-images.githubusercontent.com/8338638/132013722-b550cfd4-7744-41cf-9dec-365f2dfd8111.PNG)
Any advice for this error ? 

Sani300

**Comment by jsreynaud** [comment]
Hum... First time I see that error. Please try with a newer version of KiCadto see if it's still occur.
