### ISSUE TITLE
Vias not being generated when internal layer is of different net

### ISSUE THREAD

**Issue by W-M-D** [jsreynaud/kicad-action-scripts#40]
I have a stackup of 
GND/signal
GND
POWER
GND/signal

The via generator will not generate vias when there is a filled zone of a different net on the internal Power layer.

**Comment by jsreynaud** [comment]
Yes, it's a limitation of the current engine. It need a enhancement...

**Comment by mikprin** [comment]
Does this error caused by having PWR zone on one of the planes?

![Screenshot from 2021-12-03 16-39-41](https://user-images.githubusercontent.com/22413889/144611834-7d073afb-4f78-41ad-b0d2-bbaf03dae224.png)

**Comment by CGrassin** [comment]
I implemented a checkbox in PR #52 to generate vias when there is a filled zone of a different net on an internal layer.
