### ISSUE TITLE
TRun Time Error

### ISSUE THREAD

**Issue by DOGKiCad** [jsreynaud/kicad-action-scripts#45]
![ViaStitchingruntime-error](https://user-images.githubusercontent.com/95722844/145628957-17337876-ba26-460b-b1a7-0beff7667ed2.jpg)

Any idea what's wrong?

**Comment by jsreynaud** [comment]
Please check that you are using the right plug-in 's git branch according
your KiCad version.

**Comment by DOGKiCad** [comment]
I had the wrong branch downloaded but I've corrected that but not it not appearing in tools:
![ViaStitchingruntime-error_2](https://user-images.githubusercontent.com/95722844/145879026-b82bc5c1-57dc-4238-9cd2-db09810befa7.jpg)

**Comment by DOGKiCad** [comment]
I've corrected the branch issue but now the ViaStitching is not appearing in Tools.

This is the KiCad version 
and path is :
C:\Program Files\KiCad\share\kicad\scripting\plugins\kicad-action-scripts-5.1



Application: Pcbnew
Version: (5.1.12)-1, release build
Libraries:
    wxWidgets 3.0.5
    libcurl/7.77.0 OpenSSL/1.1.1k (Schannel) zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libpsl/0.21.1 (+libidn2/2.3.1) libssh2/1.9.0 nghttp2/1.43.0
Platform: Windows 8 (build 9200), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8)
    Boost: 1.75.0
    OpenCASCADE Technology: 7.5.0
    Curl: 7.77.0
    Compiler: GCC 10.3.0 with C++ ABI 1014

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=OFF
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=OFF
    KICAD_USE_OCC=ON
    KICAD_SPICE=ON


![ViaStitchingruntime-error_3](https://user-images.githubusercontent.com/95722844/145881448-162e582e-9f67-46c5-8baf-d5d2185e1b3c.jpg)

**Comment by jsreynaud** [comment]
Please check that you are installing this plugin in the right place. You should be able to open the plugin directory directly from pcbnew menu to be sure that you are using the good directory.

**Comment by jsreynaud** [comment]
Close because any update...
