### ISSUE TITLE
Stitching seems to avoid all keepout zones 

### ISSUE THREAD

**Issue by Jaxc** [jsreynaud/kicad-action-scripts#51]
Hello!

I made a board with some keepout zones for footprints as I have some mechanical constraints. This had the side effect that it looks like it also keeps the stitching from adding vias to these areas.
![image](https://user-images.githubusercontent.com/6492253/213907342-d6781979-c10a-4a93-b7dd-8abcc531c267.png)

**Comment by jsreynaud** [comment]
Please test with the updated version. Should be ok now.

**Comment by Jaxc** [comment]
It works now! Thanks for the superfast fix!
