### ISSUE TITLE
Remaining issues with Via Stitching in KiCad 7

### ISSUE THREAD

**Issue by CGrassin** [jsreynaud/kicad-action-scripts#55]
This issue is a follow-up to the merging of PR #54 .
There are some remaining issues with the Via Stitching plugin in KiCad 7: the patterns Concentric, Outline and Outline (No Holes) crash the plugin. This is the stack-trace: 
![image](https://user-images.githubusercontent.com/42406777/220353258-031cc211-c717-4095-9f51-d65d7f2ac8fe.png)

This is because the function ZONE.RawPolysList has been removed from the KiCad 7 API: https://docs.kicad.org/doxygen-python-7.0/classpcbnew_1_1ZONE.html I am not aware of a replacement...

**Comment by jsreynaud** [comment]
Perhaps [iterate](https://docs.kicad.org/doxygen-python-7.0/classpcbnew_1_1ZONE.html#affa63b3e95592a82b573598971c5c13a) method could be a good alternative...

**Comment by GioCC** [comment]
Is there any foreseeable fix on this issue?

**Comment by jsreynaud** [comment]
Last merge on 7.0 branch fix that.
