### ISSUE TITLE
"Random it" does not check for clearance

### ISSUE THREAD

**Issue by CGrassin** [jsreynaud/kicad-action-scripts#56]
The "random it" function does not properly account for clearance.
Example:
![Screenshot from 2023-02-21 14-19-41](https://user-images.githubusercontent.com/42406777/220359508-5a9fa00f-ab9d-421f-9873-da86274dd91a.png)
Result:
![image](https://user-images.githubusercontent.com/42406777/220359827-1f2976aa-41d3-4d57-8165-0ba02347d01a.png)

This is because the random offset is not properly bounded.

**Comment by matthuszagh** [comment]
I'm experiencing a similar issue except that the vias violate the clearance of other objects like traces.

![example](https://user-images.githubusercontent.com/7377393/221753773-56862658-e802-48cd-88dd-7d9156a36316.png)

**Comment by matthuszagh** [comment]
Actually I'm seeing this issue occasionally even if I don't select randomization. For example:

![example_nonrand](https://user-images.githubusercontent.com/7377393/221755554-8376ea3f-a80f-42cf-8752-1cd5c3d9924b.png)

![settings](https://user-images.githubusercontent.com/7377393/221755569-52f3fc1f-eb42-4f00-b0b9-efb082798d23.png)

**Comment by CGrassin** [comment]
@matthuszagh  Good catch, I managed to reproduce it, I am creating a new issue to track it.
