### ISSUE TITLE
kicad8.0RC1.91 bug

### ISSUE THREAD

**Issue by HaydenHu** [jsreynaud/kicad-action-scripts#71]
![image](https://github.com/jsreynaud/kicad-action-scripts/assets/30103277/e857a219-dcaf-4028-bf8b-5e1f53ae29d4)

**Comment by Redherring32** [comment]
Can confirm this also happens for me, but only on pre existing files made in another version of Kicad.
If I create a new file, and add an edge cut rectangle and F.Cu fill, it will happily place vias.

**Comment by HaydenHu** [comment]
> Can confirm this also happens for me, but only on pre existing files made in another version of Kicad. If I create a new file, and add an edge cut rectangle and F.Cu fill, it will happily place vias.

Isn't it supported to file on the project? It is true that new PCBs can add vias, but they will not avoid other net!

**Comment by jsreynaud** [comment]
Branch v8.0 of this project handle kicad V8. Please be sure you use this version.

**Comment by HaydenHu** [comment]
> 本项目的分支 v8.0 处理 kicad V8。请确保您使用此版本。

I've tried them all and have merged into the master

**Comment by jsreynaud** [comment]
Ok, I had updated a modification. Could you confirm it's ok ?

**Comment by HaydenHu** [comment]
> 好的，我已经更新了修改。你能确认没问题吗？

PCBs from both old and new projects will not report errors, but vias will not avoid other nets
![image](https://github.com/jsreynaud/kicad-action-scripts/assets/30103277/81fd326a-713d-45e5-b094-98effc543544)

**Comment by HaydenHu** [comment]
> Ok, I had updated a modification. Could you confirm it's ok ?

！！？

**Comment by Saatvik-Aggarwal** [comment]
I'm not able to get it to fill on a KiCad v8.0.0 project (upgraded from 7.0.3)--says 0 vias placed.

**Comment by ekartgo** [comment]
Using the latest code with 8.0 release creates a grid without avoiding any pads or traces using the grid or star options.

Unfortunate as this is a very useful tool for my prototypes and I'd be willing to donate to get it fixed.

**Comment by jsreynaud** [comment]
Let me check to fix this issue...

**Comment by HaydenHu** [comment]
> Let me check to fix this issue...

Did you find the reason for the error?

**Comment by HaydenHu** [comment]
If you have time, fix this bug, I can't do without it

**Comment by lucblender** [comment]
Using kicad 0.8.0 and v8.0 branche. I am facing the same issue with vias overlapping traces.

**Comment by VoxelTek** [comment]
I have this somewhat similar error:
![image](https://github.com/jsreynaud/kicad-action-scripts/assets/53562267/5a803f60-151c-4fec-a5c4-30cd95c503f2)

**Comment by VoxelTek** [comment]
It's worth noting that this error appears and nothing actually happens, no vias are placed. The project was started as a KiCad 8.99 project and has always been one.

**Comment by jsreynaud** [comment]
I had push an update. Please retry with last commit (on V8.0 branch of course...). And provide update of the status ;)

**Comment by VoxelTek** [comment]
I'm unsure as to the error everyone else is getting, but I still get this issue:

![image](https://github.com/jsreynaud/kicad-action-scripts/assets/53562267/9aa635cb-ec49-486b-b60b-c54e75a2b80c)

**Comment by ekartgo** [comment]
Seems to work correctly with v8 production now. Thanks for getting this resolved!
Note: This is with the Windows version.

**Comment by frizzyversion** [comment]
Hello,

I am running KiCad 8.0.1 on Windows and using the latest commit on the v8.0 branch and I am experiencing this exact issue.

![image](https://github.com/jsreynaud/kicad-action-scripts/assets/164834232/4157e028-d89e-4cc4-bd35-d41381cb82f5)

@ekartgo what version of KiCad are you using?

**Comment by lucblender** [comment]
Kicad 8.0.1, I tested the commit [ada62f8](https://github.com/jsreynaud/kicad-action-scripts/commit/ada62f8c9b0f11092514945f5352e19447a3eb48) on branch v8.0. The bug seems fixed, via doesn't overlap with traces any more!

**Comment by jsreynaud** [comment]
> Hello,
> 
> I am running KiCad 8.0.1 on Windows and using the latest commit on the v8.0 branch and I am experiencing this exact issue.
> 
> ![image](https://private-user-images.githubusercontent.com/164834232/316380777-4157e028-d89e-4cc4-bd35-d41381cb82f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTkwNTYsIm5iZiI6MTcxMTM1ODc1NiwicGF0aCI6Ii8xNjQ4MzQyMzIvMzE2MzgwNzc3LTQxNTdlMDI4LWQ4OWUtNGNjNC1iZDM1LWQ0MTM4MWNiODJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwOTI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWJlMWE3MzE2ZmI0ODE1NzE0ZDg2OTQzMmZhYzQ2YmE0YjI1ODNlMjk3N2NhNWY3NDBkY2E4OTNiMzJiZmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MzjwtBAqs71DCz3ZfYqqJrFUkz-t7QQbScQhv0iRk44)
> 
> @ekartgo what version of KiCad are you using?

Could you double check that ? It's working for at least 2 others people ...

**Comment by jsreynaud** [comment]
> I'm unsure as to the error everyone else is getting, but I still get this issue:
> 
> ![image](https://private-user-images.githubusercontent.com/53562267/316349291-9aa635cb-ec49-486b-b60b-c54e75a2b80c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTkwNTYsIm5iZiI6MTcxMTM1ODc1NiwicGF0aCI6Ii81MzU2MjI2Ny8zMTYzNDkyOTEtOWFhNjM1Y2ItZWM0OS00ODZiLWI2MGItYzU0ZTc1YTJiODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA5MjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NWI0NTA4Yzk2Y2YwZTA2ZTA0MDZmYWFlNWRkM2M0MTU1YTZiNTkxNzVmZmU0ZmEwOWM3MmE1ZTAyODQ1NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYCUvFaO7kVHaQZWNaPA8SunC3Oj5VLanQT5SHWNh7w)

I think your issue is a different problem. Please provide details on a separate issue.

**Comment by ekartgo** [comment]
> Hello,
> 
> I am running KiCad 8.0.1 on Windows and using the latest commit on the v8.0 branch and I am experiencing this exact issue.
> 
> @ekartgo what version of KiCad are you using?

8.0.1

I uninstalled the old 7 version, unzipped the 7 version, copied the new v8 CircularZone and ViaStitching folders into the same path, re-zipped the file, and installed from zip.
![stitchingv8](https://github.com/jsreynaud/kicad-action-scripts/assets/139485420/1c56c819-34bf-4943-a0b1-f8f94fd7bf4a)

**Comment by frizzyversion** [comment]
@ekartgo @jsreynaud 

It looks like it is now resolved, I am not sure what I did wrong but I deleted the plugin folder, double-checked I was on the v8.0 branch, copied the "ViaStitching" folder into the scripts folder, and it is now working. Thank you for fixing this 👍 

![image](https://github.com/jsreynaud/kicad-action-scripts/assets/164834232/f8abc57f-fd92-423a-b7de-d925b8c1430c)
